apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-platform-suite-component-zhpt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-platform-suite-component-zhpt
    app.kubernetes.io/part-of: multi-platform-suite-application-woks
  name: multi-platform-suite-component-zhpt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: multi-platform-suite-component-zhpt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: multi-platform-suite-component-zhpt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-platform-build-tenant/multi-platform-suite-application-woks/multi-platform-suite-component-zhpt@sha256:222804daf06d3af5f85a52f287ea744a4e97abdd44c60e582b97fab88a45f816
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
